### PR TITLE
Include `scm` info

### PR DESCRIPTION
**Pull request by gastaldi**
This includes the `scm` tag in the project parent

### CODE REVIEW

**Comment by melloware** [comment]
@gastaldi did you mean to close this or merge it?

**Comment by gastaldi** [comment]
I was hoping to have a look at why my script changed the formatting so much

**Comment by melloware** [comment]
Oh its OK its probably because I used tabs not spaces when I formatted it with Notepad ++.  I think you are good to do it.

**Comment by melloware** [comment]
@all-contributors add @gastaldi for infra

**Pull request merged**
